version: "3.7"
services:
  discord-runner:
    depends_on:
      - redis
    container_name: discord-runner
    build:
      context: .
    image: discord-runner:latest
    restart: always
    env_file:
      - .env
    networks:
      - runner-discord
      - redis-discord
    ports:
      - 8990:8990

  redis:
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
    container_name: redis-discord
    image: bitnami/redis:6.2-debian-10
    restart: always
    env_file:
      - redis.env
    networks:
      - redis-discord
    volumes:
      - redis-persistence:/bitnami/redis/data

networks:
  redis-discord:
  runner-discord:
    external: true

volumes:
  redis-persistence: